version: '3.8'
services:

  service-db:
    image: postgres:10
    container_name: camunda_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"