
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      hbm2ddl.auto: create

server:
  port: 9050

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
      first-name: Demo
      last-name: Demo
      email: sahalysyk02@mail.ru
